-- ----------------------------
-- 5、菜单权限表
-- ----------------------------
drop table if exists sys_menu;
create table sys_menu (
    menu_id           bigint(20)      not null auto_increment    comment '菜单ID',
    menu_name         varchar(50)     not null                   comment '菜单名称',
    parent_id         bigint(20)      default 0                  comment '父菜单ID',
    order_num         int(4)          default 0                  comment '显示顺序',
    path              varchar(200)    default ''                 comment '路由地址',
    component         varchar(255)    default null               comment '组件路径',
    query             varchar(255)    default null               comment '路由参数',
    is_frame          int(1)          default 1                  comment '是否为外链（0是 1否）',
    is_cache          int(1)          default 0                  comment '是否缓存（0缓存 1不缓存）',
    menu_type         char(1)         default ''                 comment '菜单类型（M目录 C菜单 F按钮）',
    visible           char(1)         default 0                  comment '菜单状态（0显示 1隐藏）',
    status            char(1)         default 0                  comment '菜单状态（0正常 1停用）',
    perms             varchar(100)    default null               comment '权限标识',
    icon              varchar(100)    default '#'                comment '菜单图标',
    create_by         varchar(64)     default ''                 comment '创建者',
    create_time       datetime                                   comment '创建时间',
    update_by         varchar(64)     default ''                 comment '更新者',
    update_time       datetime                                   comment '更新时间',
    remark            varchar(500)    default ''                 comment '备注',
    primary key (menu_id)
) engine=innodb auto_increment=2000 comment = '菜单权限表';

INSERT INTO `sys_menu`
VALUES (1, '基础信息', 0, 1, 'system', NULL, '', 1, 0, 'M', '0', '0', '', 'system', 'admin', CURRENT_TIMESTAMP(), '',
        NULL, '基础信息目录'),
       (2, '系统监控', 0, 3, 'monitor', NULL, '', 1, 0, 'M', '0', '0', '', 'monitor', 'admin', CURRENT_TIMESTAMP(),
        '', NULL, '系统监控目录'),
       (3, '系统工具', 0, 4, 'tool', NULL, '', 1, 0, 'M', '0', '0', '', 'tool', 'admin', CURRENT_TIMESTAMP(), '',
        NULL, '系统工具目录'),
       (4, 'RDS管理', 0, 2, 'rds', NULL, '', 1, 0, 'M', '0', '0', '', 'redis', 'admin', CURRENT_TIMESTAMP(), '', NULL,
        'RDS管理目录'),
       (5, '系统审计', 0, 5, 'log', NULL, '', 1, 0, 'M', '0', '0', '', 'log', 'admin', CURRENT_TIMESTAMP(), '', NULL,
        '系统审计菜单'),
       (100, '用户管理', 1, 1, 'user', 'system/user/index', '', 1, 0, 'C', '0', '0', 'system:user:list', 'user',
        'admin', CURRENT_TIMESTAMP(), '', NULL, '用户管理菜单'),
       (101, '角色管理', 1, 2, 'role', 'system/role/index', '', 1, 0, 'C', '0', '0', 'system:role:list', 'peoples',
        'admin', CURRENT_TIMESTAMP(), '', NULL, '角色管理菜单'),
       (102, '菜单管理', 1, 3, 'menu', 'system/menu/index', '', 1, 0, 'C', '0', '0', 'system:menu:list', 'tree-table',
        'admin', CURRENT_TIMESTAMP(), '', NULL, '菜单管理菜单'),
       (105, '字典管理', 1, 6, 'dict', 'system/dict/index', '', 1, 0, 'C', '0', '0', 'system:dict:list', 'dict',
        'admin', CURRENT_TIMESTAMP(), '', NULL, '字典管理菜单'),
       (106, '参数设置', 1, 7, 'config', 'system/config/index', '', 1, 0, 'C', '0', '0', 'system:config:list', 'edit',
        'admin', CURRENT_TIMESTAMP(), '', NULL, '参数设置菜单'),
       (107, '通知公告', 1, 8, 'notice', 'system/notice/index', '', 1, 0, 'C', '0', '0', 'system:notice:list',
        'message', 'admin', CURRENT_TIMESTAMP(), '', NULL, '通知公告菜单'),
       (109, '在线用户', 2, 4, 'online', 'monitor/online/index', '', 1, 0, 'C', '0', '0', 'monitor:online:list',
        'online', 'admin', CURRENT_TIMESTAMP(), 'admin', '2023-03-24 08:40:21', '在线用户菜单'),
       (110, '定时任务', 2, 3, 'job', 'monitor/job/index', '', 1, 0, 'C', '0', '0', 'monitor:job:list', 'job', 'admin',
        CURRENT_TIMESTAMP(), 'admin', '2023-03-24 08:40:16', '定时任务菜单'),
       (115, '表单构建', 3, 1, 'build', 'tool/build/index', '', 1, 0, 'C', '0', '0', 'tool:build:list', 'build',
        'admin', CURRENT_TIMESTAMP(), '', NULL, '表单构建菜单'),
       (118, '操作日志', 5, 1, 'operlog', 'monitor/operlog/index', '', 1, 0, 'C', '0', '0', 'monitor:operlog:list',
        'peoples', 'admin', CURRENT_TIMESTAMP(), '', NULL, '操作日志菜单'),
       (119, '登录日志', 5, 2, 'logininfor', 'monitor/logininfor/index', '', 1, 0, 'C', '0', '0',
        'monitor:logininfor:list', 'logininfor', 'admin', CURRENT_TIMESTAMP(), '', NULL, '登录日志菜单'),
       (123, '命令行维护', 4, 6, 'rdscommand', 'console/monitor/commandLine/index', '', 1, 0, 'C', '0', '0',
        'console:rdscommand:list', 'icon', 'admin', CURRENT_TIMESTAMP(), '', NULL, '数据维护'),
       (124, '数据维护', 4, 5, 'rdsdata', 'console/monitor/data/index', '', 1, 0, 'C', '0', '0', 'console:rdsdata:list',
        'date-range', 'admin', CURRENT_TIMESTAMP(), '', NULL, '命令行维护'),
       (1000, '用户查询', 100, 1, '', '', '', 1, 0, 'F', '0', '0', 'system:user:query', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1001, '用户新增', 100, 2, '', '', '', 1, 0, 'F', '0', '0', 'system:user:add', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1002, '用户修改', 100, 3, '', '', '', 1, 0, 'F', '0', '0', 'system:user:edit', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1003, '用户删除', 100, 4, '', '', '', 1, 0, 'F', '0', '0', 'system:user:remove', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1004, '用户导出', 100, 5, '', '', '', 1, 0, 'F', '0', '0', 'system:user:export', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1005, '用户导入', 100, 6, '', '', '', 1, 0, 'F', '0', '0', 'system:user:import', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1006, '重置密码', 100, 7, '', '', '', 1, 0, 'F', '0', '0', 'system:user:resetPwd', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1007, '角色查询', 101, 1, '', '', '', 1, 0, 'F', '0', '0', 'system:role:query', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1008, '角色新增', 101, 2, '', '', '', 1, 0, 'F', '0', '0', 'system:role:add', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1009, '角色修改', 101, 3, '', '', '', 1, 0, 'F', '0', '0', 'system:role:edit', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1010, '角色删除', 101, 4, '', '', '', 1, 0, 'F', '0', '0', 'system:role:remove', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1011, '角色导出', 101, 5, '', '', '', 1, 0, 'F', '0', '0', 'system:role:export', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1012, '菜单查询', 102, 1, '', '', '', 1, 0, 'F', '0', '0', 'system:menu:query', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1013, '菜单新增', 102, 2, '', '', '', 1, 0, 'F', '0', '0', 'system:menu:add', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1014, '菜单修改', 102, 3, '', '', '', 1, 0, 'F', '0', '0', 'system:menu:edit', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1015, '菜单删除', 102, 4, '', '', '', 1, 0, 'F', '0', '0', 'system:menu:remove', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1025, '字典查询', 105, 1, '#', '', '', 1, 0, 'F', '0', '0', 'system:dict:query', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1026, '字典新增', 105, 2, '#', '', '', 1, 0, 'F', '0', '0', 'system:dict:add', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1027, '字典修改', 105, 3, '#', '', '', 1, 0, 'F', '0', '0', 'system:dict:edit', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1028, '字典删除', 105, 4, '#', '', '', 1, 0, 'F', '0', '0', 'system:dict:remove', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1029, '字典导出', 105, 5, '#', '', '', 1, 0, 'F', '0', '0', 'system:dict:export', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1030, '参数查询', 106, 1, '#', '', '', 1, 0, 'F', '0', '0', 'system:config:query', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1031, '参数新增', 106, 2, '#', '', '', 1, 0, 'F', '0', '0', 'system:config:add', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1032, '参数修改', 106, 3, '#', '', '', 1, 0, 'F', '0', '0', 'system:config:edit', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1033, '参数删除', 106, 4, '#', '', '', 1, 0, 'F', '0', '0', 'system:config:remove', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1034, '参数导出', 106, 5, '#', '', '', 1, 0, 'F', '0', '0', 'system:config:export', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1035, '公告查询', 107, 1, '#', '', '', 1, 0, 'F', '0', '0', 'system:notice:query', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1036, '公告新增', 107, 2, '#', '', '', 1, 0, 'F', '0', '0', 'system:notice:add', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1037, '公告修改', 107, 3, '#', '', '', 1, 0, 'F', '0', '0', 'system:notice:edit', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1038, '公告删除', 107, 4, '#', '', '', 1, 0, 'F', '0', '0', 'system:notice:remove', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1039, '操作查询', 118, 1, '#', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:query', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1040, '操作删除', 118, 2, '#', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:remove', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1041, '日志导出', 118, 3, '#', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:export', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1042, '登录查询', 119, 1, '#', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:query', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1043, '登录删除', 119, 2, '#', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:remove', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1044, '日志导出', 119, 3, '#', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:export', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1046, '在线查询', 109, 1, '#', '', '', 1, 0, 'F', '0', '0', 'monitor:online:query', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1047, '批量强退', 109, 2, '#', '', '', 1, 0, 'F', '0', '0', 'monitor:online:batchLogout', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1048, '单条强退', 109, 3, '#', '', '', 1, 0, 'F', '0', '0', 'monitor:online:forceLogout', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1049, '任务查询', 110, 1, '#', '', '', 1, 0, 'F', '0', '0', 'monitor:job:query', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1050, '任务新增', 110, 2, '#', '', '', 1, 0, 'F', '0', '0', 'monitor:job:add', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1051, '任务修改', 110, 3, '#', '', '', 1, 0, 'F', '0', '0', 'monitor:job:edit', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1052, '任务删除', 110, 4, '#', '', '', 1, 0, 'F', '0', '0', 'monitor:job:remove', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1053, '状态修改', 110, 5, '#', '', '', 1, 0, 'F', '0', '0', 'monitor:job:changeStatus', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1054, '任务导出', 110, 6, '#', '', '', 1, 0, 'F', '0', '0', 'monitor:job:export', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1073, 'RDS服务', 4, 4, 'rdsservice', 'console/rdsservice/index', NULL, 1, 0, 'C', '0', '0',
        'console:rdsservice:list', 'server', 'admin', CURRENT_TIMESTAMP(), '', NULL,
        'RDS服务菜单'),
       (1074, 'RDS服务查询', 1073, 1, '#', '', NULL, 1, 0, 'F', '0', '0', 'console:rdsservice:query', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1075, 'RDS服务新增', 1073, 2, '#', '', NULL, 1, 0, 'F', '0', '0', 'console:rdsservice:add', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1076, 'RDS服务修改', 1073, 3, '#', '', NULL, 1, 0, 'F', '0', '0', 'console:rdsservice:edit', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1077, 'RDS服务删除', 1073, 4, '#', '', NULL, 1, 0, 'F', '0', '0', 'console:rdsservice:remove', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1096, '中心服务', 4, 2, 'centerservice', 'console/centerservice/index', NULL, 1, 0, 'C', '0', '0',
        'console:centerservice:list', 'exit-fullscreen', 'admin', CURRENT_TIMESTAMP(), '', NULL,
        '中心服务菜单'),
       (1097, '中心服务查询', 1096, 1, '#', '', NULL, 1, 0, 'F', '0', '0', 'console:centerservice:query', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1098, '中心服务新增', 1096, 2, '#', '', NULL, 1, 0, 'F', '0', '0', 'console:centerservice:add', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1099, '中心服务修改', 1096, 3, '#', '', NULL, 1, 0, 'F', '0', '0', 'console:centerservice:edit', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1100, '中心服务删除', 1096, 4, '#', '', NULL, 1, 0, 'F', '0', '0', 'console:centerservice:remove', '#', 'admin',
        CURRENT_TIMESTAMP(), '', NULL, ''),
       (1102, 'RDS服务监控', 2, 1, 'rdsmonitor', 'console/rdsmonitor/index', NULL, 1, 0, 'C', '0', '0',
        'console:rdsmonitor:list', 'monitor', 'admin', CURRENT_TIMESTAMP(), '', NULL, 'RDS服务监控菜单');

