# kubectl -n rds apply -f memdb.yaml
# kubectl -n rds scale statefulset rdsmemdb --replicas 8
# kubectl -n rds scale statefulset rdsmemdb --replicas 5
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rdsmemdb
spec:
  serviceName: rds-memdb
  replicas: 6
  selector:
    matchLabels:
      app: rdsmemdb
  template:
    metadata:
      labels:
        app: rdsmemdb
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                      - rdsmemdb
                topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 300
      containers:
        - name: rdsmemdb
          lifecycle:
            preStop:
              exec:
                command: ["./StopServer.sh"]
          imagePullPolicy: Always
          image: 192.168.0.89:80/library/tongrds-node:2.2.1.4
          ports:
            - containerPort: 6200
              name: service
            - containerPort: 6379
              name: simulation
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CENTER_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: tong-rds-center
                  key: center.k8s.service
            - name: CONFIG_VOLUME_PATH
              value: "/projected-volume"
          volumeMounts:
            - name: config
              mountPath: /projected-volume
      volumes:
        - name: config
          configMap:
            name: tong-rds-node

      imagePullSecrets:
        - name: registry-pull-secret

